modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="coffeecraft"
version="${file.jarVersion}"
displayName="CoffeeCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/coffeecraft"
logoFile="denseki.png"
credits="Credits to Jüdacraz for textures and models."
authors="Akrivus"
description='''
Adds coffee to Minecraft.
'''

[[dependencies.coffeecraft]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.coffeecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
